### ISSUE TITLE
Supporting a non-ISO compliant date format using a ValueTransformer

### ISSUE THREAD

**Issue by enhancient** [3lvis/SYNCPropertyMapper#144]
I have a date format I need to support as follows:

2016/11/21 14:33:59 -0500

It is not ISO compliant, so I wrote a ValueTransformer as per:
https://github.com/SyncDB/SYNCPropertyMapper#dealing-with-bad-apis

I converted the date string to an ISO 8601 compliant string in my ValueTransformer by setting hyper.valueTransformer user info key on the attribute to my ValueTransformer, The transformer itself is being called and working, however I am getting nil values for the attributes. 

After debugging it looks like in:

` NSManagedObject+SYNCPropertyMapperHelpers.m in (id)valueForAttributeDescription:(NSAttributeDescription *)attributeDescription usingRemoteValue:(id)remoteValue `

if there is a custom transformer then 'value' variable is set to the transformed value as follows:

`value = [transformer transformedValue:remoteValue];`

However this value is then set to nil further on by:

 `
} else if (stringValueAndDateAttribute) {
        value = [NSDate dateFromDateString:remoteValue];
`

This is because remoteValue is still the non ISO 8601 compliant string.

I got it working by changing the value that the transformer changes to:

`remoteValue = [transformer transformedValue:remoteValue];`

I'm not sure if this is the best solution - can you suggest if this was a bug and the above fixes it?

By the way, I didn't use a Transformable attribute type based on your advice in: https://github.com/SyncDB/Sync/issues/300

And I also tried creating a ValueTransformer that converted my date string to NSDate using:

NSDate.init(fromISO8601String: dateString)

But I was also get nil dates - perhaps something similar was happening to that above.

Many thanks!

**Comment by 3lvis** [comment]
Hi @enhancient,

Thanks for reaching out. Would it be possible that you can share a sample code or project of this with me? I need to be able to reproduce it in order to be able to fix it.

**Comment by enhancient** [comment]
Hi @3lvis,

Thanks for your response. I've attached sample JSON, my ValueTransformer and Core Data model. 

Hopefully that's enough to help you reproduce.

Thanks for looking into it!

[RavIt.xcdatamodel.zip](https://github.com/SyncDB/SYNCPropertyMapper/files/633736/RavIt.xcdatamodel.zip)
[TransformerRavelryDateStringToISO8601.swift.zip](https://github.com/SyncDB/SYNCPropertyMapper/files/633741/TransformerRavelryDateStringToISO8601.swift.zip)
[test.json.zip](https://github.com/SyncDB/SYNCPropertyMapper/files/633743/test.json.zip)
