### ISSUE TITLE
DateParser doesn't work correctly, if the date nearly 1/1/1970.

### ISSUE THREAD

**Issue by mrDyos** [3lvis/SYNCPropertyMapper#147]
1/1/1970 15:00 of milliseconds is 54000000. But length of 54000000 less than the length of 1441843200, therefore 54000000 not converted into seconds and the result will 09/18/1971 00:00.

I change function (NSDate *)dateFromUnixTimestampString:(NSString *)unixTimestamp:

```objective-c
+ (NSDate *)dateFromUnixTimestampString:(NSString *)unixTimestamp {
    NSString *parsedString = unixTimestamp;
    
    if (([parsedString length] <= 3) || ([parsedString length] <= 4 && [parsedString characterAtIndex:0] == '-')) {
        parsedString = @"0";
    }
    else
    {
        parsedString = [parsedString substringToIndex:[parsedString length] - 3];
    }

    NSNumberFormatter *numberFormatter = [NSNumberFormatter new];
    numberFormatter.numberStyle = NSNumberFormatterDecimalStyle;
    NSNumber *unixTimestampNumber = [numberFormatter numberFromString:parsedString];
    NSDate *date = [[NSDate alloc] initWithTimeIntervalSince1970:unixTimestampNumber.doubleValue];

    return date;
}
```

**Comment by 3lvis** [comment]
I think the current implementation is correct. I used [this service](http://www.epochconverter.com/) to convert `54000000` and I'm getting exactly what the current implementation gives.

```swift
let resultDate = NSDate(fromDateString: "54000000") as! Date
print(resultDate)
// 1971-09-18 00:00:00 +0000
```

<img width="677" alt="screen shot 2017-02-04 at 8 56 35 am" src="https://cloud.githubusercontent.com/assets/1088217/22616897/e6945ba8-eab7-11e6-9bd0-6810467587d8.png">

**Comment by mrDyos** [comment]
If this number of seconds it is the correct result.
```objective-c
let resultDate = NSDate(fromDateString: "54000000") as! Date
print(resultDate)
// 1971-09-18 00:00:00 +0000
```

[This service](http://www.epochconverter.com) works with second.
In my system all the time is stored in milliseconds. 
When the datetime is 1970-1-1 15:00 (in milliseconds 54000000) your code does not convert from milliseconds to seconds, and result is 1971-09-18 00:00:00 +0000 - not right
When the datetime is 2017-2-4 15:00 (in milliseconds - 1486220400000) your code convert to second, and result 2017-02-04 15:00:00 +0000 - right

54000000 in millisecond is 1/1/1970 15:00
![q](https://cloud.githubusercontent.com/assets/25540185/22617734/c5352cb6-eb17-11e6-9ab5-b77314586909.png)

To work correctly on all range date, you should always convert to seconds.
